# Generated by Django 4.2.11 on 2024-03-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
