# Generated by Django 4.2.11 on 2024-03-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
