# Generated by Django 4.2.11 on 2024-03-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
