# Generated by Django 4.2.11 on 2024-03-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='userregister',
            name='password2',
            field=models.CharField(default='repeat password', max_length=100),
        ),
    ]
