# Generated by Django 4.2.11 on 2024-03-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0008_rename_password_userregister_password1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='user_image',
        ),
    ]
