# Generated by Django 4.2.11 on 2024-03-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0009_remove_userregister_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password2',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='password1',
        ),
    ]
