# Generated by Django 4.2.11 on 2024-03-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0010_rename_password2_userregister_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='password2',
            field=models.CharField(default='repeat password', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
