# Generated by Django 4.2.11 on 2024-03-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0011_userregister_password2_alter_userregister_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='username',
            field=models.CharField(default='full name', max_length=100),
        ),
    ]
