# Generated by Django 4.2.11 on 2024-03-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0012_userregister_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRegister',
            new_name='User',
        ),
    ]
