# Generated by Django 4.2.11 on 2024-03-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainhub', '0013_rename_userregister_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
