# Generated by Django 4.2.11 on 2024-03-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
