# Generated by Django 4.2.11 on 2024-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_review_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='title', max_length=100, unique=True),
        ),
    ]
