# Generated by Django 4.2.11 on 2024-03-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
